# Библиотека NumPy

Перед использованием нужно импортировать NumPy

In [1]:
import numpy as np


Пример инициализации одномерного массива:

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

Обращение к элементам одномерного массива: 

In [3]:
print(a[0])

1


Пример инициализации двумерного массива:

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a[1][2])

7


In [6]:
a[1]

array([5, 6, 7, 8])

a.ndim - этот атрибут возвращает количество измерений массива.

In [7]:
a.ndim

2

a.shape - возвращает кортеж, указывающий размер массива в каждом измерении.

In [8]:
a.shape

(3, 4)

a.size - возвращает общее количество элементов массива (фактически это произведение элементов, возвращаемое shape) 

In [9]:
a.size

12

a.dtype - возвращает тип элементов массива. Кроме стандартных типов, в NumPy есть собственные типы данных.

In [10]:
a.dtype

dtype('int64')

a.diagonal() - возвращает диагональ матрицы

In [11]:
a.diagonal()

array([ 1,  6, 11])

a.sum() - возвращает сумму всех элементов массива

In [12]:
a.sum()

np.int64(78)

a.mean() - возвращает среднее арифметическое всех элементов массива.

In [13]:
a.mean()

np.float64(6.5)

np.zeros((n, m)) - создаёт массив размером n*m, заполненный нулями. 

In [14]:
a = np.zeros((2, 4), int)
print(a)

[[0 0 0 0]
 [0 0 0 0]]


np.ones((n, m)) -  создаёт массив размером n*m, заполненный единицами. 

In [15]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty((n, m)) - возвращает пустой (не инициализированный) массив размером n*m. Он заполнен "мусором". Используя такие массивы будете осторожны, а лучше всегда задавайте начальные значения элементов массива. Атрибуты такие же как и у предыдущих функций.

In [16]:
a = np.empty((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

np.copy(a) - создаёт копию массива a.

In [17]:
a = np.array([[1, 2, 3, 4.0],
[5, 6, 7, 8],
[9, 10, 11, 12]])
b = np.copy(a)
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

np.sort(a) - эта функция возвращает отсортированную копию входного массива. 

In [18]:
np.sort(b)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

Пример 1

Найти минимальный и максимальный элементы по каждому столбцу и строке

In [20]:
print('Min of each row',a.min(axis=1))
print('Max of each row',a.max(axis=1))
print('Min of each column',a.min(axis=0))
print('Max of each column',a.max(axis=0))

Min of each row [1. 5. 9.]
Max of each row [ 4.  8. 12.]
Min of each column [1. 2. 3. 4.]
Max of each column [ 9. 10. 11. 12.]


Пример 2

Преобразование одномерного массива в двумерный

In [ ]:
np_array = np.arange(10)
print("Исходный массив : \n", np_array)
new_array = np.reshape(np_array, (2, 5))
print("\n Измененный массив с 2 строками и 5 столбцами : \n", new_array)
new_array = np_array.reshape(5, 2)
print("\n Измененный массив с 5 строками и 2 столбцами : \n", new_array)

Исходный массив : 
 [0 1 2 3 4 5 6 7 8 9]

 Измененный массив с 2 строками и 5 столбцами : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

 Измененный массив с 5 строками и 2 столбцами : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
